"""Ajout du champ email au modèle User

Revision ID: 06b76c5f2a5d
Revises: d5f484ab46df
Create Date: 2024-10-28 14:48:55.752417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b76c5f2a5d'
down_revision = 'd5f484ab46df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certif',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certif_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certif_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certif')
    # ### end Alembic commands ###
