"""Increase description size to TEXT

Revision ID: c610edb88bfa
Revises: 06b76c5f2a5d
Create Date: 2024-10-29 14:32:12.054744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c610edb88bfa'
down_revision = '06b76c5f2a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certif', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projet', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('certif', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
